//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGT.PNRProcessing.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PNRProcessingDBEntities : DbContext
    {
        public PNRProcessingDBEntities()
            : base("name=PNRProcessingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblPCCConfiguration> tblPCCConfigurations { get; set; }
        public virtual DbSet<tblPNRProcessingTrace> tblPNRProcessingTraces { get; set; }
        public virtual DbSet<tblTicketingFlowConfiguration> tblTicketingFlowConfigurations { get; set; }
    }
}
