//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGT.PNRProcessing.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPNRProcessingTrace
    {
        public string PNRProcessingTraceId { get; set; }
        public string Recloc { get; set; }
        public string PCC { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsProcessComplete { get; set; }
        public int NoOfFares { get; set; }
        public int NoOfTicketedFares { get; set; }
        public string Error { get; set; }
        public Nullable<System.DateTime> PNRCaptureDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
