//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGT.PNRProcessing.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public int QueueId { get; set; }
        public string QueueRefName { get; set; }
        public string GDS { get; set; }
        public string PCC { get; set; }
        public string QueueNoCategory { get; set; }
        public Nullable<int> ScanFreq { get; set; }
        public string QueueFunction { get; set; }
        public Nullable<int> RobotId { get; set; }
        public string HAP { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
    
        public virtual Robot Robot { get; set; }
    }
}
