//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGT.PNRProcessing.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Robot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Robot()
        {
            this.Queues = new HashSet<Queue>();
        }
    
        public int RobotId { get; set; }
        public string RobotName { get; set; }
        public string Remarks { get; set; }
        public string CommRemarks { get; set; }
        public Nullable<bool> AvailAVL { get; set; }
        public string FOP { get; set; }
        public string Fare { get; set; }
        public Nullable<bool> MCTError { get; set; }
        public Nullable<int> SuccessQueueNo { get; set; }
        public string SuccessMsg { get; set; }
        public Nullable<int> FailureQueueNo { get; set; }
        public string FailureMsg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queue> Queues { get; set; }
    }
}
