//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGT.PNRProcessing.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTicketingFlowConfiguration
    {
        public int TicketingflowId { get; set; }
        public string TicketingflowName { get; set; }
        public int PCCID { get; set; }
        public string PreFormatedRemark { get; set; }
        public string CommissionRemarkFormat { get; set; }
        public Nullable<int> CommissionPct { get; set; }
        public string AllowedFOP { get; set; }
        public string AllowedFareType { get; set; }
        public bool IsAVLCheck { get; set; }
        public bool IsMCTCheck { get; set; }
        public int SuccessQNo { get; set; }
        public string SuccessMsg { get; set; }
        public int FailQNo { get; set; }
        public string FailMsg { get; set; }
        public int TargetQNo { get; set; }
        public int ScanFrequency { get; set; }
    }
}
